### ISSUE TITLE
Use modern CMake

### ISSUE THREAD

**Issue by Flamefire** [morganbengtsson/mos#26]
Just from your Readme:

```
target_link_libraries(${PROJECT_NAME} mos)
target_include_directories(${PROJECT_NAME} PUBLIC externals/mos/include)
```

The 2nd line should not be required if `mos` had setup its include dirs. Use `target_include_directories` and `PUBLIC/PRIVATE/INTERFACE` for all `target_*` functions. See "Effective CMake" by Daniel Pfeiffer,

**Comment by morganbengtsson** [comment]
Thanks, should be a bit cleaner now:
https://github.com/morganbengtsson/mos/commit/4a2efb888399fc3525d8c1b69cf7f6c49ac943a6
https://github.com/morganbengtsson/mos/commit/95aa800148def771b807639f6e16330663034556
Quite sure I could read up on CMake a bit more though.

**Comment by Flamefire** [comment]
Related: Is (e.g.) glm a public dependency or is it only used internally?
There is `add_definitions(-DGLM_FORCE_RADIANS)` at the top, if glm is public you should use `target_compile_definitions(target PUBLIC ...`) if not use `PRIVATE` and make the include directory `PRIVATE` too. Similar for others in `target_include_directories`: Decide and define what is only internally used and what is included in the external interface.
`-DMOS_EFX` can also be a `PRIVATE` in `target_compile_definitions`
