### ISSUE TITLE
[Feature Request]add SSAO or HBAO

### ISSUE THREAD

**Issue by ghost** [morganbengtsson/mos#27]
i don't know if it gonna be important or not, the current features mos have right now is already impressive, its small but the rendering is like wow, but i don't see any ambient occlusion (except ao map in the material slot) i know using baked ao is a good idea but i think its gonna be time consuming to bake them one by one. so how about add the real-time one?
i will just leave something [here](https://github.com/asylum2010/Asylum_Tutorials/tree/master/ShaderTutors/54_GTAO) whos know you will be interested :trollface:

**Comment by Kenji245** [comment]
i wish i could implement it myself but i dont have many experience with graphic programming, even i keeping failed when i try to follow some tutorial over the internet so i hope you dont mind i made request 😃
